using SchemaTypist.DatabaseMetadata;

namespace SchemaTypist.Dml
{
    public class InsertArgumentsValidator : IDmlArgumentsValidator
    {
        public bool IsValid(ColumnDefinition column, object val)
        {
            return !column.Metadata.IsAutogenerated && (!column.Metadata.IsNullable || val != null);
        }
    }
}