using SchemaTypist.DatabaseMetadata;

namespace SchemaTypist.Dml
{
    public class UpdateArgumentsValidator : IDmlArgumentsValidator
    {
        public bool IsValid(ColumnDefinition column, object val)
        {
            return !column.Metadata.IsAutogenerated;
        }
    }
}