// ReSharper disable UnusedAutoPropertyAccessor.Global
namespace SchemaTypist.DatabaseMetadata
{
    public class ColumnMetadata
    {
        public ColumnMetadata(string sqlName, string sqlDataType, int characterMaximumLength, int numericPrecision,
            int numericScale, bool isNullable, string defaultValue)
        {
            SqlName = sqlName;
            SqlDataType = sqlDataType;
            CharacterMaximumLength = characterMaximumLength;
            NumericPrecision = numericPrecision;
            NumericScale = numericScale;
            IsNullable = isNullable;
            DefaultValue = defaultValue;
        }

        public string SqlName { get; }
        public string SqlDataType { get; }
        public int CharacterMaximumLength { get; }
        public int NumericPrecision { get; }
        public int NumericScale { get; }
        public bool IsNullable { get; }
        public string DefaultValue { get; }

        public bool IsAutogenerated { get; } = false;
    }
}