name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore all dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal
      - name: Pack SchemaTypist
        run: dotnet pack -c Release -o ./nupkgs --no-build src/SchemaTypist/SchemaTypist.csproj
      - name: Pack SchemaTypist.Cli
        run: dotnet pack -c Release -o ./nupkgs --no-build src/SchemaTypist/SchemaTypist.Cli.csproj
      - name: Pack SchemaTypist.MSBuild
        run: dotnet pack -c Release -o ./nupkgs --no-build src/SchemaTypist/SchemaTypist.MSBuild.csproj
      - name: Publish
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_PUBLISH_API_KEY }}  --skip-duplicate -s https://api.nuget.org/v3/index.json